[dev]
	command = "npm run start:vite"
	publish = "dist"
	targetPort = 5173
	functionsPort = 5174
	port = 9000
	framework = "#custom"

[build]
	command = "npm run build:vite"
	publish = "dist"

[functions]
	directory = "./src/functions"
	node_bundler = "esbuild"

[[redirects]]
	from = "/api/*"
	to = "/.netlify/functions/:splat"
	status = 200

[[redirects]]
	from = "/*"
	to = "/index.html"
	status = 200

[template.environment]
	OMDB_API_KEY = "OMDB API Key"
	LASTFM_API_KEY = "last.fm API key"
	GIANTBOMB_API_KEY = "Giant Bomb API key"